backend:
  name: "github"
  repo: "gopaljigaur/gopaljigaur"

media_folder: "/images/uploads"
media_library:
  name: "cloudinary"
  config:
    cloud_name: "gopalji.ml"
    api_key: "puiWUW3vkHvEUTZ01Yx0nLR_si8"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Projects"
        name: "projects"
        file: "site/content/projects.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}