backend:
  name: "github"
  repo: "gopaljigaur/gopaljigaur"
  branch: "master"
  api_root: "https://api.github.com"
  site_domain: "gopalji.ml"
  base_url: "https://api.netlify.com"
  auth_endpoint: "auth"
  label_prefix: "netlify_cms/"

media_folder: "/images/uploads"
media_library:
  name: "cloudinary"
  config:
    cloud_name: "gopalji.ml"
    api_key: "puiWUW3vkHvEUTZ01Yx0nLR_si8"
collections:
  - label: "Pages"
    name: "pages"
